# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# This is some other workflow to run on all pull-requests
name: Some other checker

on:
  workflow_call:
#  pull_request:
#    branches:
#      - main

jobs:
  # Look for the string "FATAL" in README
  fatal_readme_check:
    name: Fatal README Check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        keywords: "FATAL" "DEADLY"
    steps:
      - name: Checkout RTL repo
        uses: actions/checkout@v4

      - name: Run Script
        run: |
          set -e
          fatal_count=$(grep -c ${{ matrix.keywords }} $GITHUB_WORKSPACE/README.md || exit 0)
          if [[ $fatal_count -gt 0 ]]; then
            echo "Found ${{ matrix.keywords }} in README"
            exit 1
          fi
          echo "Did not find ${{ matrix.keywords }} in README"
  verify:
    name: Verify
    runs-on: ubuntu-22.04
    needs: fatal_readme_check
    if: ${{ !cancelled() }}
    steps:
      - name: Printout
        run: |
          echo "Result [ ${{ needs.fatal_readme_check.result }}]"
          if [[ "${{ needs.fatal_readme_check.result }}" != "success" ]]; then
            echo "Bad"
            exit 1
          else
            echo "Good"
            exit 0
          fi
