# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# This is the top-level workflow to run on all pull-requests
name: Pull Request Checker

on:
  workflow_dispatch:
  pull_request:

env:
  actors: ( 'calebofearth' 'blargh' 'cookie-monsta' )
jobs:
  # Look for any files called error
  err_file_check:
    name: Error File Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout RTL repo
        uses: actions/checkout@v4

      - name: Run Script
        run: |
          set -e
          skippers=${{ env.actors }}
          for skipper in "${skippers[@]}"; do
            if [[ ${{ github.actor }} == "${skipper}" ]]; then
              exit 0
            fi
          done
          file_count=$(find $GITHUB_WORKSPACE/ -type f -name "*error*" | wc -l)
          if [[ $file_count -gt 0 ]]; then
            echo "Found error files"
            exit 1
          fi
          echo "Did not find any error files"
